# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------


HEADERS += ./weathershowdlg.h
SOURCES += ./main.cpp \
    ./weathershowdlg.cpp
FORMS += ./weathershowdlg.ui
RESOURCES += weathershowdlg.qrc
